spring:
  profiles:
    active: h2
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 15
    hibernate:
      ddl-auto: validate

---
spring.config.activate.on-profile: tc-postgres
spring.datasource.url: jdbc:tc:postgresql:13-alpine:///postgres
---
spring.config.activate.on-profile: local-postgres
spring.datasource:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: postgres